export const plans = [
  {
    name: "Free",
    monthlyPrice: "Free",
    yearlyPrice: "Free",
    description: "Great for trying out DocUnpack.",
    features: [
      "10 Simplified docs output",
      "5 follow-up Q&A",
      "Export simplified docs (pdf/text/md)",
      "Basic AI speed",
    ],
    button: "Get Started",
    highlighted: false,
    comingSoon: false,
    dodoId: null,
  },
  {
    name: "Basic",
    monthlyPrice: "$9/mo",
    yearlyPrice: "$90/yr",
    description: "For casual devs who need more follow-ups.",
    features: [
      "100 Simplified docs output",
      "50 follow-up Q&A",
      "Faster AI responses",
      "Export simplified docs (pdf/text/md)",
    ],
    // button: "Upgrade to Basic",
    button: "Coming Soon",
    highlighted: true,
    comingSoon: true,
    dodoId: {
      monthly: "pdt_FCUDc6TryvYbtHPZIn13e",
      yearly: "pdt_uTezw214Hcw1MdzNiLAOH",
    },
  },
  {
    name: "Pro",
    monthlyPrice: "$29/mo",
    yearlyPrice: "$290/yr",
    description: "Best for devs & teams who rely on it daily.",
    features: [
      "Unlimited Simplified docs output",
      "Unlimited follow-up Q&A",
      "Faster AI responses",
      "Export simplified docs (pdf/text/md)",
      "Dedicated support",
    ],
    // button: "Get Pro",
    button: "Coming Soon",
    highlighted: false,
    comingSoon: true,
    dodoId: {
      monthly: "pdt_BP02fccEk57LwHyJ62dFf",
      yearly: "pdt_97jPOb6Fwt9PGdySwTTNp",
    },
  },
];
